services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    ports:
      - "5438:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
